//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectUserRegistration
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;

    public partial class tbl_User
    {
        public int UserId { get; set; }
        [Display(Name = "User")]
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> IsIntrestedIncSharp { get; set; }
        public Nullable<bool> IsIntrestedInJava { get; set; }
        public Nullable<bool> IsIntrestedInPython { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string ImagePath { get; set; }
        public HttpPostedFileBase UserImageFile { get; set; }
        public virtual tbl_City tbl_City { get; set; }
        public string DobStr { get;  set; }
        public SelectList CityList { get; internal set; }
    }
}
