//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectUserRegistration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Categorys
    {
        public int CategoryId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    }
}
